---
name: Passport CI

on:
  push:
    paths:
      - ".github/workflows/base.yml"
      - ".github/workflows/passport.yml"
      - "crates/passport/**"
      - "proto/passport.proto"
      - "Cargo.lock"
      - "Cargo.toml"
  pull_request:
    paths:
      - ".github/workflows/base.yml"
      - ".github/workflows/passport.yml"
      - "crates/passport/**"
      - "proto/passport.proto"
      - "Cargo.lock"
      - "Cargo.toml"
  workflow_dispatch: # Allows to trigger the workflow manually in GitHub UI

jobs:
  base:
    uses: ./.github/workflows/base.yml
    with:
      image_name: ${{ github.repository }}/passport
      registry: ghcr.io
      package: passport
      workdir: crates/passport
    secrets: inherit
