---
name: Passport API CI

on:
  push:
    branches:
      - master
    tags:
      - "passport-api-v*"
    paths:
      - ".github/workflows/base.yml"
      - ".github/workflows/passport-api.yml"
      - "crates/passport-api/**"
      - "proto/passport.proto"
      - "Cargo.lock"
      - "Cargo.toml"
  pull_request:
    branches:
      - master
    paths:
      - ".github/workflows/base.yml"
      - ".github/workflows/passport-api.yml"
      - "crates/passport-api/**"
      - "proto/passport.proto"
      - "Cargo.lock"
      - "Cargo.toml"
  workflow_dispatch: # Allows to trigger the workflow manually in GitHub UI

jobs:
  base:
    uses: ./.github/workflows/base.yml
    with:
      image_name: ${{ github.repository }}/passport-api
      registry: ghcr.io
      package: passport-api
      workdir: crates/passport-api
    secrets: inherit
